train:
  config_path: resnet101/oxford_pets_binary_resnet101.yaml
  output_dir: resnet101/model_trained/mlops
  tracking_uri: file:./resnet101/mlruns

dataops:
  config_path: resnet101/oxford_pets_binary_resnet101.yaml
  preprocess_report_path: monitoring/dataops_preprocess_report.json

monitoring:
  inference_log_path: monitoring/inference_events.jsonl
  feedback_log_path: monitoring/feedback_events.jsonl
  software_report_path: monitoring/software_metrics_report.json
  drift_report_path: monitoring/drift_report.json
  model_health_report_path: monitoring/model_health_report.json
